// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools 2015 v1.7.160
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VfpLanguage
{
    static class Vsix
    {
        public const string Id = "f4ab1e64-5555-4f06-bad9-bf414f4b3ccc"; // bbb"; // bbb";
        public const string Name = "VfpLanguage VS12";
        public const string Description = "Visual FoxPro .prg files editor";
        public const string Language = "en-US";
        public const string Version = "0.2";
        public const string Author = "Andrius K";
        public const string Tags = "Visual FoxPro prg editor";
        
    }
}