#pragma checksum "Native\NoBorder.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "2C86B170BFC0E124B61515A845CEF959D01BCB16"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;


namespace VfpProj {
    
    
    /// <summary>
    /// NoBorder
    /// </summary>
    public partial class NoBorder : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 22 "Native\NoBorder.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel titleBar;
        
        #line default
        #line hidden
        
        
        #line 29 "Native\NoBorder.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button cmdClose;
        
        #line default
        #line hidden
        
        
        #line 31 "Native\NoBorder.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ContentControl content;
        
        #line default
        #line hidden
        
        
        #line 34 "Native\NoBorder.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle topLeft;
        
        #line default
        #line hidden
        
        
        #line 35 "Native\NoBorder.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle top;
        
        #line default
        #line hidden
        
        
        #line 36 "Native\NoBorder.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle topRight;
        
        #line default
        #line hidden
        
        
        #line 37 "Native\NoBorder.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle right;
        
        #line default
        #line hidden
        
        
        #line 38 "Native\NoBorder.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle bottomRight;
        
        #line default
        #line hidden
        
        
        #line 39 "Native\NoBorder.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle bottom;
        
        #line default
        #line hidden
        
        
        #line 40 "Native\NoBorder.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle bottomLeft;
        
        #line default
        #line hidden
        
        
        #line 41 "Native\NoBorder.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle left;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/VfpProj2;component/native/noborder.xaml", System.UriKind.Relative);
            
            #line 1 "Native\NoBorder.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.titleBar = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 2:
            this.cmdClose = ((System.Windows.Controls.Button)(target));
            return;
            case 3:
            this.content = ((System.Windows.Controls.ContentControl)(target));
            return;
            case 4:
            this.topLeft = ((System.Windows.Shapes.Rectangle)(target));
            return;
            case 5:
            this.top = ((System.Windows.Shapes.Rectangle)(target));
            return;
            case 6:
            this.topRight = ((System.Windows.Shapes.Rectangle)(target));
            return;
            case 7:
            this.right = ((System.Windows.Shapes.Rectangle)(target));
            return;
            case 8:
            this.bottomRight = ((System.Windows.Shapes.Rectangle)(target));
            return;
            case 9:
            this.bottom = ((System.Windows.Shapes.Rectangle)(target));
            return;
            case 10:
            this.bottomLeft = ((System.Windows.Shapes.Rectangle)(target));
            return;
            case 11:
            this.left = ((System.Windows.Shapes.Rectangle)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

