//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfp15Test.VfpService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VfpService", Namespace="http://schemas.datacontract.org/2004/07/VfpProj.Wcf")]
    [System.SerializableAttribute()]
    public partial class VfpService : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActiveProjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirectoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HWndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusBarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.KeyValuePair<string, object>[] VFPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActiveProject {
            get {
                return this.ActiveProjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ActiveProjectField, value) != true)) {
                    this.ActiveProjectField = value;
                    this.RaisePropertyChanged("ActiveProject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Directory {
            get {
                return this.DirectoryField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectoryField, value) != true)) {
                    this.DirectoryField = value;
                    this.RaisePropertyChanged("Directory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HWnd {
            get {
                return this.HWndField;
            }
            set {
                if ((this.HWndField.Equals(value) != true)) {
                    this.HWndField = value;
                    this.RaisePropertyChanged("HWnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusBar {
            get {
                return this.StatusBarField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusBarField, value) != true)) {
                    this.StatusBarField = value;
                    this.RaisePropertyChanged("StatusBar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, object>[] VFP {
            get {
                return this.VFPField;
            }
            set {
                if ((object.ReferenceEquals(this.VFPField, value) != true)) {
                    this.VFPField = value;
                    this.RaisePropertyChanged("VFP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CsObj", Namespace="http://schemas.datacontract.org/2004/07/VfpProj")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vfp15Test.VfpService.VfpService))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.KeyValuePair<string, object>[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.KeyValuePair<string, object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vfp15Test.VfpService.CsForm))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.IntPtr))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Exception))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    public partial class CsObj : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object CmdFormField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.IntPtr hWndField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object CmdForm {
            get {
                return this.CmdFormField;
            }
            set {
                if ((object.ReferenceEquals(this.CmdFormField, value) != true)) {
                    this.CmdFormField = value;
                    this.RaisePropertyChanged("CmdForm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.IntPtr hWnd {
            get {
                return this.hWndField;
            }
            set {
                if ((this.hWndField.Equals(value) != true)) {
                    this.hWndField = value;
                    this.RaisePropertyChanged("hWnd");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CsForm", Namespace="http://schemas.datacontract.org/2004/07/VfpProj")]
    [System.SerializableAttribute()]
    public partial class CsForm : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Exception LastErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception LastError {
            get {
                return this.LastErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.LastErrorField, value) != true)) {
                    this.LastErrorField = value;
                    this.RaisePropertyChanged("LastError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VfpService.IVfpService")]
    public interface IVfpService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVfpService/Load", ReplyAction="http://tempuri.org/IVfpService/LoadResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vfp15Test.VfpService.VfpService))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.KeyValuePair<string, object>[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.KeyValuePair<string, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vfp15Test.VfpService.CsObj))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vfp15Test.VfpService.CsForm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.IntPtr))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object Load(object obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVfpService/Load", ReplyAction="http://tempuri.org/IVfpService/LoadResponse")]
        System.Threading.Tasks.Task<object> LoadAsync(object obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVfpService/Eval", ReplyAction="http://tempuri.org/IVfpService/EvalResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vfp15Test.VfpService.VfpService))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.KeyValuePair<string, object>[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.KeyValuePair<string, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vfp15Test.VfpService.CsObj))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vfp15Test.VfpService.CsForm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.IntPtr))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Collections.Generic.KeyValuePair<string, object>[] Eval(object obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVfpService/Eval", ReplyAction="http://tempuri.org/IVfpService/EvalResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<string, object>[]> EvalAsync(object obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVfpService/DoCmd", ReplyAction="http://tempuri.org/IVfpService/DoCmdResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vfp15Test.VfpService.VfpService))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.KeyValuePair<string, object>[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.KeyValuePair<string, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vfp15Test.VfpService.CsObj))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vfp15Test.VfpService.CsForm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.IntPtr))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object DoCmd(string cmd, object[] parm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVfpService/DoCmd", ReplyAction="http://tempuri.org/IVfpService/DoCmdResponse")]
        System.Threading.Tasks.Task<object> DoCmdAsync(string cmd, object[] parm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVfpService/DoCompile", ReplyAction="http://tempuri.org/IVfpService/DoCompileResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vfp15Test.VfpService.VfpService))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.KeyValuePair<string, object>[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.KeyValuePair<string, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vfp15Test.VfpService.CsObj))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vfp15Test.VfpService.CsForm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.IntPtr))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object DoCompile(string file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVfpService/DoCompile", ReplyAction="http://tempuri.org/IVfpService/DoCompileResponse")]
        System.Threading.Tasks.Task<object> DoCompileAsync(string file);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVfpServiceChannel : Vfp15Test.VfpService.IVfpService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VfpServiceClient : System.ServiceModel.ClientBase<Vfp15Test.VfpService.IVfpService>, Vfp15Test.VfpService.IVfpService {
        
        public VfpServiceClient() {
        }
        
        public VfpServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VfpServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VfpServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VfpServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object Load(object obj) {
            return base.Channel.Load(obj);
        }
        
        public System.Threading.Tasks.Task<object> LoadAsync(object obj) {
            return base.Channel.LoadAsync(obj);
        }
        
        public System.Collections.Generic.KeyValuePair<string, object>[] Eval(object obj) {
            return base.Channel.Eval(obj);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<string, object>[]> EvalAsync(object obj) {
            return base.Channel.EvalAsync(obj);
        }
        
        public object DoCmd(string cmd, object[] parm) {
            return base.Channel.DoCmd(cmd, parm);
        }
        
        public System.Threading.Tasks.Task<object> DoCmdAsync(string cmd, object[] parm) {
            return base.Channel.DoCmdAsync(cmd, parm);
        }
        
        public object DoCompile(string file) {
            return base.Channel.DoCompile(file);
        }
        
        public System.Threading.Tasks.Task<object> DoCompileAsync(string file) {
            return base.Channel.DoCompileAsync(file);
        }
    }
}
